### ISSUE TITLE
CPS-2 graphical corruption on left side of screen

### ISSUE THREAD

**Issue by MJY71** [jotego/jtcps#137]
The most recent CPS-2 update (jtcps2_20220627	08141df) exhibits graphical corruption in the left-most column of pixels on several (all?) games. Some layers do not extend all the way to the left edge of the screen, and there is occasional color shifting with some layers in that first column. It is very noticeable during the Street Fighter Alpha/Zero 3 intro sequence with the numerous scrolling scene changes.

**Comment by jotego** [comment]
From sfa3:

![20220702_083917-screen](https://user-images.githubusercontent.com/1863036/176993418-2ac8e0ba-3130-4b7d-acc6-357a5b69769a.png)
The object layer seems to start off a bit too early (at least 2 pixels)

In the Ryu image, there is a gap because the object layer (upper face) is off to the left by at least 1 pixel. The lower face is SCR2

![20220702_084002-screen](https://user-images.githubusercontent.com/1863036/176993454-fdd3161b-1aeb-4b4c-b1df-ecd7be10b1c4.png)

From sfa2
Chun Li's is drawn in the OBJ layer and starts a bit too early
![20220702_083710-screen](https://user-images.githubusercontent.com/1863036/176993470-f0fea190-d8dc-4911-8959-61ab2847f197.png)

**Comment by jotego** [comment]
The problem came because the cawing fix had moved the SCR layers ahead one pixel, and the CPS2 colmix was modified to add a pixel delay to the scroll (see #117). After reverting the cawing fix edd0cb9, the SCR layer had to be taken without delay in CPS2 colmix. e289fc5 fixes this.
